# fly.toml app configuration file generated for group-sports-queue on 2024-01-04T22:36:22-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "group-sports-queue"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
